# .github/workflows/ci-cd.yml
name: Next.js CI/CD Pipeline

on:
  push:
    branches:
      - master  # Runs on pushes to the master branch
  pull_request:
    branches:
      - master  # Runs on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js project
        run: npm run build # Make sure you have a build script defined in your package.json

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test # Ensure that your tests are properly set up in your Next.js project

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} # Ensure you have Vercel CLI and token configured in your secrets